### ISSUE TITLE
’swin‘ train without pth 

### ISSUE THREAD

**Issue by ghost** [olivia-w12/PatchDCT#8]
I want to use swinb to train the model and report the error 'Checkpoint swin_base_patch4_window7_224_22k_d2.pth not found!', where can I get the weight file?

**Comment by olivia-w12** [comment]
We use the same initial file as [Mask Transfiner](https://github.com/SysCV/transfiner), so you can download the pretrained checkpoint in [this page](https://drive.google.com/file/d/12IGYQOa-nlpFhTbgdifbMnSkcke3lmCO/view)

**Comment by ghost** [comment]
thanks!
